syntax = "proto3";
package storage;

service StorageService {
  rpc UploadAttach(UploadRequest) returns (UploadResponse);
  rpc GetAttachList(GetListRequest) returns (AttachListResponse);
  rpc DeleteAttach(DeleteRequest) returns (CommonResponse);
  rpc GetDownloadUrl(GetUrlRequest) returns (UrlResponse);
}

message UploadRequest {
  string asset_biz_id = 1;
  string attach_name = 2;
  bytes file_data = 3;
  int32 attach_type = 4;
  string upload_user_biz_id = 5;
}

message UploadResponse {
  string attach_biz_id = 1;
  string file_path = 2;
}

message GetListRequest {
  string asset_biz_id = 1;
}

message AttachInfo {
  string biz_id = 1;
  string asset_biz_id = 2;
  string attach_name = 3;
  string attach_path = 4;
  int32 attach_type = 5;
  int64 file_size = 6;
  string create_time = 7;
}

message AttachListResponse {
  repeated AttachInfo list = 1;
  int32 total = 2;
}

message DeleteRequest {
  string attach_biz_id = 1;
}

message CommonResponse {
  bool success = 1;
  string msg = 2;
}

message GetUrlRequest {
  string attach_biz_id = 1;
}

message UrlResponse {
  string download_url = 1;
}